In [1]:
%load_ext jupyter_black

In [4]:
import warnings
import sys
import os

In [5]:
CURRENT_DIRECTORY = os.getcwd()
PROJECT_ROOT = os.path.abspath(
    os.path.join(CURRENT_DIRECTORY, "../pipelines/rapidapi_jobs_posting/")
)
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)
    print(f"{PROJECT_ROOT} was added to sys.path")

REPO_ROOT = os.path.abspath(os.path.join(CURRENT_DIRECTORY, ".."))
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)
    print(f"{REPO_ROOT} was added to sys.path")

/home/jovyan/work/repos/jobs-research/pipelines/rapidapi_jobs_posting was added to sys.path
/home/jovyan/work/repos/jobs-research was added to sys.path

In [15]:
import pandas as pd

from mappings import *

In [7]:
CITY_CLUSTERS

{'Rhein-Neckar': {'heidelberg', 'ludwigshafen', 'mannheim', 'walldorf'},
 'Berlin': {'berlin'},
 'Munich': {'munchen', 'munich', 'münchen'},
 'Other': {'oder'},
 'Frankfurt': {'frankfurt'},
 'Cologne': {'cologne', 'köln'},
 'Düsseldorf': {'duesseldorf', 'düsseldorf'},
 'Stuttgart': {'stuttgart'},
 'Hamburg': {'hamburg'},
 'Hanover': {'hannover', 'hanover'},
 'Nuremberg': {'nuremberg', 'nürnberg'},
 'Bonn': {'bonn'},
 'Leipzig': {'leipzig'},
 'Dresden': {'dresden'},
 'Essen': {'essen'},
 'Karlsruhe': {'karlsruhe'},
 'Bremen': {'bremen'},
 'Potsdam': {'potsdam'},
 'Heidelberg': {'heidelberg'}}

In [14]:
city_clusters_table = []
for result, keywords_set in CITY_CLUSTERS.items():
    for keyword in list(keywords_set):
        city_clusters_table.append([keyword, result])

city_clusters_table

[['heidelberg', 'Rhein-Neckar'],
 ['mannheim', 'Rhein-Neckar'],
 ['walldorf', 'Rhein-Neckar'],
 ['ludwigshafen', 'Rhein-Neckar'],
 ['berlin', 'Berlin'],
 ['munich', 'Munich'],
 ['munchen', 'Munich'],
 ['münchen', 'Munich'],
 ['oder', 'Other'],
 ['frankfurt', 'Frankfurt'],
 ['köln', 'Cologne'],
 ['cologne', 'Cologne'],
 ['düsseldorf', 'Düsseldorf'],
 ['duesseldorf', 'Düsseldorf'],
 ['stuttgart', 'Stuttgart'],
 ['hamburg', 'Hamburg'],
 ['hanover', 'Hanover'],
 ['hannover', 'Hanover'],
 ['nuremberg', 'Nuremberg'],
 ['nürnberg', 'Nuremberg'],
 ['bonn', 'Bonn'],
 ['leipzig', 'Leipzig'],
 ['dresden', 'Dresden'],
 ['essen', 'Essen'],
 ['karlsruhe', 'Karlsruhe'],
 ['bremen', 'Bremen'],
 ['potsdam', 'Potsdam'],
 ['heidelberg', 'Heidelberg']]

In [20]:
city_clusters_df = pd.DataFrame(city_clusters_table, columns=["keyword", "result"])

In [22]:
city_clusters_df.set_index("keyword")

                    result
keyword
heidelberg    Rhein-Neckar
mannheim      Rhein-Neckar
walldorf      Rhein-Neckar
ludwigshafen  Rhein-Neckar
berlin              Berlin
munich              Munich
munchen             Munich
münchen             Munich
oder                 Other
frankfurt        Frankfurt
köln               Cologne
cologne            Cologne
düsseldorf      Düsseldorf
duesseldorf     Düsseldorf
stuttgart        Stuttgart
hamburg            Hamburg
hanover            Hanover
hannover           Hanover
nuremberg        Nuremberg
nürnberg         Nuremberg
bonn                  Bonn
leipzig            Leipzig
dresden            Dresden
essen                Essen
karlsruhe        Karlsruhe
bremen              Bremen
potsdam            Potsdam
heidelberg      Heidelberg

In [23]:
POSITIONS

[MappingDict(mapping_dict={'Data Engineer': 'Data Engineer', 'Data Anal': 'Data Analyst', 'Data Scien': 'Data Scientist', 'Data Manager': 'Data Manager', 'Product Manager': 'Product Manager', 'Project Manager': 'Project Manager', 'Product Owner': 'Product Owner', 'ML Ops': 'ML Ops', 'Platform Engineer': 'IaC Specialist', 'Software Engineer': 'Software Engineer', 'Network Engineer': 'Network Engineer', 'Facility Engineer': 'Facility Engineer', 'Governence': 'Data Protection/Governance Specialist', 'Governance': 'Data Protection/Governance Specialist', 'Data Privacy': 'Data Protection/Governance Specialist', 'Data Protection': 'Data Protection/Governance Specialist', 'Data Entry': 'Data Entry Specialist', 'Data Quality': 'Data Quality Specialist', 'BI Engineer': 'Data Engineer', 'BI Anal': 'Data Analyst', 'Marketing Anal': 'Data Analyst', 'Machine Learning Engineer': 'ML Ops', 'Data Steward': 'Data Manager'}, case_sensitive=False, spaces_sensitive=False),
 MappingDict(mapping_dict={'AI Engineer': 'ML Ops', 'Data Research': 'Data Analyst', 'Data Modelling': 'Data Manager', 'Data Mapping': 'Data Manager', 'Validation': 'Data Quality Specialist', 'Analyst': 'Data Analyst'}, case_sensitive=False, spaces_sensitive=False),
 MappingDict(mapping_dict={'Infrastructure Engineer': 'IaC Specialist', 'Architect': 'Architect', 'Data Center Technician': 'Facility Engineer', 'DevOps': 'IaC Specialist', 'Tutor': 'Tutor/Teacher', 'Teacher': 'Tutor/Teacher', 'Consultant': 'Consultant/Advisor', 'Advisor': 'Consultant/Advisor'}, case_sensitive=False, spaces_sensitive=False),
 MappingDict(mapping_dict={'DE': 'Data Engineer', 'IaC': 'IaC Specialist', 'DA': 'Data Analyst', 'DS': 'Data Scientist'}, case_sensitive=True, spaces_sensitive=True)]

In [28]:
positions_table = []
for mapping_dict in POSITIONS:
    for keyword, result in mapping_dict.mapping_dict.items():
        positions_table.append(
            [
                keyword,
                result,
                mapping_dict.case_sensitive,
                mapping_dict.spaces_sensitive,
            ]
        )

pd.DataFrame(
    positions_table, columns=["keyword", "result", "case_sensitive", "spaces_sensitive"]
).set_index("keyword")

,result,case_sensitive,spaces_sensitive
keyword,,,
Data Engineer,Data Engineer,False,False
Data Anal,Data Analyst,False,False
Data Scien,Data Scientist,False,False
Data Manager,Data Manager,False,False
Product Manager,Product Manager,False,False
Project Manager,Project Manager,False,False
Product Owner,Product Owner,False,False
ML Ops,ML Ops,False,False
Platform Engineer,IaC Specialist,False,False
Software Engineer,Software Engineer,False,False
Network Engineer,Network Engineer,False,False
Facility Engineer,Facility Engineer,False,False
Governence,Data Protection/Governance Specialist,False,False
Governance,Data Protection/Governance Specialist,False,False
Data Privacy,Data Protection/Governance Specialist,False,False
Data Protection,Data Protection/Governance Specialist,False,False
Data Entry,Data Entry Specialist,False,False
Data Quality,Data Quality Specialist,False,False
BI Engineer,Data Engineer,False,False
BI Anal,Data Analyst,False,False
Marketing Anal,Data Analyst,False,False
Machine Learning Engineer,ML Ops,False,False
Data Steward,Data Manager,False,False
AI Engineer,ML Ops,False,False
Data Research,Data Analyst,False,False
Data Modelling,Data Manager,False,False
Data Mapping,Data Manager,False,False
Validation,Data Quality Specialist,False,False
Analyst,Data Analyst,False,False
Infrastructure Engineer,IaC Specialist,False,False
Architect,Architect,False,False
Data Center Technician,Facility Engineer,False,False
DevOps,IaC Specialist,False,False
Tutor,Tutor/Teacher,False,False
Teacher,Tutor/Teacher,False,False
Consultant,Consultant/Advisor,False,False
Advisor,Consultant/Advisor,False,False
DE,Data Engineer,True,True
IaC,IaC Specialist,True,True
DA,Data Analyst,True,True
DS,Data Scientist,True,True